--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JavierLeon9966/BedrockBreaker
build-by-default: true
branches:
- master
- PM4
projects:
  BedrockBreaker:
    path: ""
    icon: "resources/Bedrock.png"
    libs:
      - src: ParoxityTeam/Commando/Commando
        branch: PM-4.0
        version: ^3.0.0
...
