--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JavierLeon9966/BedrockBreaker
build-by-default: true
branches:
- master
projects:
  BedrockBreaker:
    path: ""
    icon: "resources/Bedrock.png"
    libs:
      - src: ACM-PocketMine-MP/Commando/Commando # Temporary until the original updates
        version: ^3.2.0
        branch: PM5
      - src: Cosmoverse/BlockData/BlockData
        version: ^0.0.1
      - src: sylvrs/libMarshal/libMarshal
        branch: "feature/virion"
        version: ^1.4.3
...
