name: BedrockBreaker
main: JavierLeon9966\BedrockBreaker\Main
author: JavierLeon9966
api: 5.0.0
mcpe-protocols: [594, 618, 630, 649]
version: 4.5.0
description: Allow breaking bedrock with TNT
permissions:
  bedrockbreaker.command.breakable:
    description: Permission to use breakable command
    default: op
  bedrockbreaker.command.bbresistance:
    description: Permission to use bbresistance command
    default: op
  bedrockbreaker.command.bbexplosions:
    description: Permission to use bbexplosioms command
    default: op
